# This file is used only for demonstration purposes. Do not run it

from methods import *

# Initial data
users = [
    {"username": "john_doe", "email": "john.doe@example.com"},
    {"username": "jane_smith", "email": "jane.smith@example.com"},
    {"username": "robert_brown", "email": "robert.brown@example.com"},
    {"username": "emily_jones", "email": "emily.jones@example.com"},
    {"username": "michael_taylor", "email": "michael.taylor@example.com"}
]

targets = [
    {
        "username": "john_doe", "month": "August", 
        "back_and_shoulder_target": 25, "arms_target": 20, "core_target": 18, "legs_target": 30,
        "back_and_shoulder_progress": 28, "arms_progress": 12, "core_progress": 10, "legs_progress": 31
    },    
    {
        "username": "jane_smith", "month": "August", 
        "back_and_shoulder_target": 21, "arms_target": 25, "core_target": 30, "legs_target": 25,
        "back_and_shoulder_progress": 19, "arms_progress": 24, "core_progress": 31, "legs_progress": 17
    },
    {
        "username": "robert_brown", "month": "August", 
        "back_and_shoulder_target": 20, "arms_target": 28, "core_target": 22, "legs_target": 26,
        "back_and_shoulder_progress": 17, "arms_progress": 29, "core_progress": 22, "legs_progress": 23
    },
    {
        "username": "emily_jones", "month": "August", 
        "back_and_shoulder_target": 28, "arms_target": 25, "core_target": 24, "legs_target": 29,
        "back_and_shoulder_progress": 26, "arms_progress": 27, "core_progress": 17, "legs_progress": 28
    },
    {
        "username": "michael_taylor", "month": "August", 
        "back_and_shoulder_target": 24, "arms_target": 22, "core_target": 23, "legs_target": 17,
        "back_and_shoulder_progress": 23, "arms_progress": 25, "core_progress": 21, "legs_progress": 16
    }
]

muscles = [
    {
        "muscle_name": "Trapezius",
        "explanation": "A large, triangular muscle located in your upper back and neck",
        "body_section_id": 1
    },
    {
        "muscle_name": "Shoulder",
        "explanation": "Includes the anterior deltoid, lateral deltoid, and posterior deltoid",
        "body_section_id": 1
    },
    {
        "muscle_name": "Latissimus Dorsi",
        "explanation": "The muscle is a large flat muscle in the lower thorax",
        "body_section_id": 1
    },
    {
        "muscle_name": "Biceps",
        "explanation": "A large muscle in the upper arm which turns the hand to face palm uppermost and flexes the arm and forearm.",
        "body_section_id": 2
    },
    {
        "muscle_name": "Triceps",
        "explanation": "A large, thick muscle on the dorsal part of the upper arm.",
        "body_section_id": 2
    },
    {
        "muscle_name": "Forearms",
        "explanation": "Part of the arms between the elbow and the wrist",
        "body_section_id": 2
    },
    {
        "muscle_name": "Rectus Abdominis (Abs)",
        "explanation": "Slung between the ribs and the pubic bone at the front of the pelvis",
        "body_section_id": 3
    },
    {
        "muscle_name": "External Abdominal Oblique (Side Abs)",
        "explanation": "Are part of the abdominal muscles responsible for movement of the trunk, spine, and core",
        "body_section_id": 3
    },
    {
        "muscle_name": "Front Thigh (Quadriceps)",
        "explanation": "The quadriceps femoris muscle is part of the anterior muscles of the thigh, along with the sartorius muscle.",
        "body_section_id": 4
    },
    {
        "muscle_name": "Back Thigh (Hamstrings)",
        "explanation": "The hamstring muscles are a group of three muscles that run along the back of the thigh from the hip to just below the knee.",
        "body_section_id": 4
    },
    {
        "muscle_name": "Calves (Gastrocnemius and Soleus)",
        "explanation": "It starts just below from behind your knee, runs down your lower leg and connects to your Achilles tendon above your heel",
        "body_section_id": 4
    }
]

exercises = [
    {"exercise_name": "Babel Upright Row", "reps": 10, "sets": 2, "muscle_id": 1, "intensity_id": 3},
    {"exercise_name": "Cable Upright Row", "reps": 10, "sets": 3, "muscle_id": 1, "intensity_id": 3},
    {"exercise_name": "Elevated Pike Press", "reps": 12, "sets": 3, "muscle_id": 1, "intensity_id": 2},
    {"exercise_name": "Dumbell Shrug", "reps": 15, "sets": 4, "muscle_id": 1, "intensity_id": 1},
    {"exercise_name": "Cable 30 Degree Shrug", "reps": 15, "sets": 4, "muscle_id": 1, "intensity_id": 1},
    {"exercise_name": "Pullups", "reps": 12, "sets": 3, "muscle_id": 1, "intensity_id": 2},
    {"exercise_name": "Barbel Incline Bench Press", "reps": 12, "sets": 3, "muscle_id": 2, "intensity_id": 3},
    {"exercise_name": "Barbel Overhead Bench Press", "reps": 12, "sets": 3, "muscle_id": 2, "intensity_id": 3},
    {"exercise_name": "Spider Pushups", "reps": 10, "sets": 4, "muscle_id": 2, "intensity_id": 2},
    {"exercise_name": "Lateral Raises", "reps": 12, "sets": 4, "muscle_id": 2, "intensity_id": 2},
    {"exercise_name": "Front Raises", "reps": 12, "sets": 4, "muscle_id": 2, "intensity_id": 2},
    {"exercise_name": "Dumbell Incline Bench Press", "reps": 10, "sets": 3, "muscle_id": 2, "intensity_id": 2},
    {"exercise_name": "Cable Rope Face Pulls", "reps": 15, "sets": 4, "muscle_id": 2, "intensity_id": 1},
    {"exercise_name": "Chin-Ups", "reps": 10, "sets": 3, "muscle_id": 3, "intensity_id": 3},
    {"exercise_name": "Cable Bent Over Bar Pullover", "reps": 10, "sets": 4, "muscle_id": 3, "intensity_id": 1},
    {"exercise_name": "Babel Bent Over Row", "reps": 10, "sets": 3, "muscle_id": 3, "intensity_id": 3},
    {"exercise_name": "Inverted Row", "reps": 15, "sets": 4, "muscle_id": 3, "intensity_id": 1},
    {"exercise_name": "Machine Assisted Chin-Ups", "reps": 12, "sets": 3, "muscle_id": 3, "intensity_id": 2},
    {"exercise_name": "Cable Lat Prayer", "reps": 12, "sets": 3, "muscle_id": 3, "intensity_id": 2},
    {"exercise_name": "Bicep Curls", "reps": 12, "sets": 3, "muscle_id": 4, "intensity_id": 1},
    {"exercise_name": "Hammer Curls", "reps": 12, "sets": 3, "muscle_id": 4, "intensity_id": 1},
    {"exercise_name": "Concentration Curls", "reps": 10, "sets": 3, "muscle_id": 4, "intensity_id": 2},
    {"exercise_name": "Incline Dumbell Curls", "reps": 10, "sets": 3, "muscle_id": 4, "intensity_id": 2},
    {"exercise_name": "Barbel Curls", "reps": 8, "sets": 4, "muscle_id": 4, "intensity_id": 3},
    {"exercise_name": "Preacher Curls", "reps": 8, "sets": 4, "muscle_id": 4, "intensity_id": 3},
    {"exercise_name": "Tricep Dips", "reps": 12, "sets": 3, "muscle_id": 5, "intensity_id": 1},
    {"exercise_name": "Overhead Tricep Extensions", "reps": 12, "sets": 3, "muscle_id": 5, "intensity_id": 1},
    {"exercise_name": "Tricep Pushdowns", "reps": 10, "sets": 3, "muscle_id": 5, "intensity_id": 2},
    {"exercise_name": "Skull Crushers", "reps": 10, "sets": 3, "muscle_id": 5, "intensity_id": 2},
    {"exercise_name": "Close Grip Bench Press", "reps": 8, "sets": 4, "muscle_id": 5, "intensity_id": 3},
    {"exercise_name": "Tricep Kickbacks", "reps": 8, "sets": 4, "muscle_id": 5, "intensity_id": 3},
    {"exercise_name": "Wrist Curls (Palms Up)", "reps": 15, "sets": 3, "muscle_id": 6, "intensity_id": 1},
    {"exercise_name": "Reverse Wrist Curls", "reps": 15, "sets": 3, "muscle_id": 6, "intensity_id": 1},
    {"exercise_name": "Farmer's Walk", "reps": 15, "sets": 3, "muscle_id": 6, "intensity_id": 2},
    {"exercise_name": "Hammer Grip Barbell Holds", "reps": 12, "sets": 3, "muscle_id": 6, "intensity_id": 2},
    {"exercise_name": "Tower Pullups", "reps": 8, "sets": 4, "muscle_id": 6, "intensity_id": 3},
    {"exercise_name": "Plate Pinches", "reps": 8, "sets": 4, "muscle_id": 6, "intensity_id": 3},
    {"exercise_name": "Basic Crunches", "reps": 15, "sets": 3, "muscle_id": 7, "intensity_id": 1},
    {"exercise_name": "Heel Touches", "reps": 15, "sets": 3, "muscle_id": 7, "intensity_id": 1},
    {"exercise_name": "Leg Raises", "reps": 12, "sets": 3, "muscle_id": 7, "intensity_id": 2},
    {"exercise_name": "Russian Twists", "reps": 20, "sets": 3, "muscle_id": 7, "intensity_id": 2},
    {"exercise_name": "Hanging Leg Raises", "reps": 10, "sets": 4, "muscle_id": 7, "intensity_id": 3},
    {"exercise_name": "Bicycle Crunches", "reps": 20, "sets": 4, "muscle_id": 7, "intensity_id": 3},
    {"exercise_name": "Standing Oblique Crunches", "reps": 15, "sets": 3, "muscle_id": 8, "intensity_id": 1},
    {"exercise_name": "Side Bends (Dumbbell)", "reps": 12, "sets": 3, "muscle_id": 8, "intensity_id": 2},
    {"exercise_name": "Cable Woodchoppers", "reps": 10, "sets": 4, "muscle_id": 8, "intensity_id": 3},
    {"exercise_name": "Twisting Hanging Leg Raises", "reps": 10, "sets": 4, "muscle_id": 8, "intensity_id": 3},
    {"exercise_name": "Bodyweight Squats", "reps": 15, "sets": 3, "muscle_id": 9, "intensity_id": 1},
    {"exercise_name": "Lunges (Each Side)", "reps": 12, "sets": 3, "muscle_id": 9, "intensity_id": 1},
    {"exercise_name": "Walking Lunges", "reps": 12, "sets": 3, "muscle_id": 9, "intensity_id": 2},
    {"exercise_name": "Goblet Squats", "reps": 12, "sets": 3, "muscle_id": 9, "intensity_id": 2},
    {"exercise_name": "Leg Press", "reps": 10, "sets": 4, "muscle_id": 9, "intensity_id": 3},
    {"exercise_name": "Deadlifts", "reps": 8, "sets": 4, "muscle_id": 9, "intensity_id": 3},
    {"exercise_name": "Calf Raises", "reps": 15, "sets": 4, "muscle_id": 10, "intensity_id": 1},
    {"exercise_name": "Seated Calf Raises", "reps": 15, "sets": 4, "muscle_id": 10, "intensity_id": 1},
    {"exercise_name": "Single Leg Calf Raises", "reps": 10, "sets": 4, "muscle_id": 10, "intensity_id": 2},
    {"exercise_name": "Donkey Calf Raises", "reps": 15, "sets": 3, "muscle_id": 10, "intensity_id": 2},
    {"exercise_name": "Squats", "reps": 10, "sets": 4, "muscle_id": 10, "intensity_id": 3},
    {"exercise_name": "Sled Pulls", "reps": 8, "sets": 4, "muscle_id": 10, "intensity_id": 3}
]

body_sections = [
    {"body_section_name": "Back and Shoulder"},
    {"body_section_name": "Arms"},
    {"body_section_name": "Core"},
    {"body_section_name": "Legs"}
]

workouts = [
    {"workout_name": "Advanced Back and Shoulder", "intensity": 3, "body_section_id": 1},
    {"workout_name": "Intermediate Back and Shoulder", "intensity": 2, "body_section_id": 1},
    {"workout_name": "Beginner Back and Shoulder", "intensity": 1, "body_section_id": 1},
    {"workout_name": "Advanced Arms", "intensity": 3, "body_section_id": 2},
    {"workout_name": "Intermediate Arms", "intensity": 2, "body_section_id": 2},
    {"workout_name": "Beginner Arms", "intensity": 1, "body_section_id": 2},
    {"workout_name": "Advanced Core", "intensity": 3, "body_section_id": 3},
    {"workout_name": "Intermediate Core", "intensity": 2, "body_section_id": 3},
    {"workout_name": "Beginner Core", "intensity": 1, "body_section_id": 3},
    {"workout_name": "Advanced Legs", "intensity": 3, "body_section_id": 4},
    {"workout_name": "Intermediate Legs", "intensity": 2, "body_section_id": 4},
    {"workout_name": "Beginner Legs", "intensity": 1, "body_section_id": 4},
]

sessions = [
    {"username": "john_doe", "date": "2024-08-01", "workout_id": 1, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-01", "workout_id": 6, "target_id": 2},
    {"username": "john_doe", "date": "2024-08-01", "workout_id": 3, "target_id": 3},
    {"username": "john_doe", "date": "2024-08-01", "workout_id": 3, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-01", "workout_id": 2, "target_id": 1},
    {"username": "jane_smith", "date": "2024-08-01", "workout_id": 5, "target_id": 2},
    {"username": "jane_smith", "date": "2024-08-01", "workout_id": 2, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-01", "workout_id": 2, "target_id": 4},
    {"username": "robert_brown", "date": "2024-08-01", "workout_id": 1, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-01", "workout_id": 5, "target_id": 2},
    {"username": "robert_brown", "date": "2024-08-01", "workout_id": 2, "target_id": 3},
    {"username": "robert_brown", "date": "2024-08-01", "workout_id": 2, "target_id": 4},
    {"username": "emily_jones", "date": "2024-08-01", "workout_id": 2, "target_id": 1},
    {"username": "emily_jones", "date": "2024-08-01", "workout_id": 4, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-01", "workout_id": 1, "target_id": 3},
    {"username": "emily_jones", "date": "2024-08-01", "workout_id": 2, "target_id": 4},
    {"username": "michael_taylor", "date": "2024-08-01", "workout_id": 1, "target_id": 1},
    {"username": "michael_taylor", "date": "2024-08-01", "workout_id": 6, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-01", "workout_id": 3, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-01", "workout_id": 1, "target_id": 4},
    {"username": "john_doe", "date": "2024-08-02", "workout_id": 2, "target_id": 3},
    {"username": "robert_brown", "date": "2024-08-02", "workout_id": 5, "target_id": 2},
    {"username": "robert_brown", "date": "2024-08-02", "workout_id": 1, "target_id": 3},
    {"username": "emily_jones", "date": "2024-08-02", "workout_id": 3, "target_id": 4},
    {"username": "michael_taylor", "date": "2024-08-02", "workout_id": 3, "target_id": 4},
    {"username": "john_doe", "date": "2024-08-03", "workout_id": 2, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-03", "workout_id": 2, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-03", "workout_id": 1, "target_id": 4},
    {"username": "emily_jones", "date": "2024-08-03", "workout_id": 2, "target_id": 1},
    {"username": "emily_jones", "date": "2024-08-03", "workout_id": 4, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-03", "workout_id": 2, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-03", "workout_id": 3, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-04", "workout_id": 2, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-04", "workout_id": 6, "target_id": 2},
    {"username": "john_doe", "date": "2024-08-04", "workout_id": 3, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-04", "workout_id": 2, "target_id": 1},
    {"username": "jane_smith", "date": "2024-08-04", "workout_id": 5, "target_id": 2},
    {"username": "jane_smith", "date": "2024-08-04", "workout_id": 1, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-04", "workout_id": 1, "target_id": 4},
    {"username": "robert_brown", "date": "2024-08-04", "workout_id": 1, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-04", "workout_id": 5, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-04", "workout_id": 1, "target_id": 4},
    {"username": "michael_taylor", "date": "2024-08-04", "workout_id": 6, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-04", "workout_id": 1, "target_id": 3},
    {"username": "john_doe", "date": "2024-08-05", "workout_id": 3, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-05", "workout_id": 6, "target_id": 2},
    {"username": "john_doe", "date": "2024-08-05", "workout_id": 1, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-05", "workout_id": 1, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-05", "workout_id": 4, "target_id": 2},
    {"username": "robert_brown", "date": "2024-08-05", "workout_id": 1, "target_id": 3},
    {"username": "emily_jones", "date": "2024-08-05", "workout_id": 1, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-05", "workout_id": 1, "target_id": 1},
    {"username": "michael_taylor", "date": "2024-08-05", "workout_id": 6, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-05", "workout_id": 1, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-05", "workout_id": 3, "target_id": 4},
    {"username": "john_doe", "date": "2024-08-06", "workout_id": 1, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-06", "workout_id": 2, "target_id": 3},
    {"username": "john_doe", "date": "2024-08-06", "workout_id": 2, "target_id": 4},
    {"username": "robert_brown", "date": "2024-08-06", "workout_id": 3, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-06", "workout_id": 1, "target_id": 4},
    {"username": "emily_jones", "date": "2024-08-06", "workout_id": 3, "target_id": 1},
    {"username": "emily_jones", "date": "2024-08-06", "workout_id": 5, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-06", "workout_id": 3, "target_id": 4},
    {"username": "michael_taylor", "date": "2024-08-06", "workout_id": 2, "target_id": 3},
    {"username": "john_doe", "date": "2024-08-07", "workout_id": 4, "target_id": 2},
    {"username": "jane_smith", "date": "2024-08-07", "workout_id": 1, "target_id": 1},
    {"username": "jane_smith", "date": "2024-08-07", "workout_id": 5, "target_id": 2},
    {"username": "jane_smith", "date": "2024-08-07", "workout_id": 3, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-07", "workout_id": 2, "target_id": 4},
    {"username": "robert_brown", "date": "2024-08-07", "workout_id": 6, "target_id": 2},
    {"username": "robert_brown", "date": "2024-08-07", "workout_id": 1, "target_id": 3},
    {"username": "emily_jones", "date": "2024-08-07", "workout_id": 2, "target_id": 1},
    {"username": "emily_jones", "date": "2024-08-07", "workout_id": 2, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-07", "workout_id": 4, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-07", "workout_id": 3, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-08", "workout_id": 2, "target_id": 1},
    {"username": "jane_smith", "date": "2024-08-08", "workout_id": 4, "target_id": 2},
    {"username": "jane_smith", "date": "2024-08-08", "workout_id": 2, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-08", "workout_id": 3, "target_id": 4},
    {"username": "robert_brown", "date": "2024-08-08", "workout_id": 3, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-08", "workout_id": 1, "target_id": 4},
    {"username": "emily_jones", "date": "2024-08-08", "workout_id": 3, "target_id": 1},
    {"username": "emily_jones", "date": "2024-08-08", "workout_id": 2, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-08", "workout_id": 2, "target_id": 1},
    {"username": "michael_taylor", "date": "2024-08-08", "workout_id": 2, "target_id": 4},
    {"username": "john_doe", "date": "2024-08-09", "workout_id": 2, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-09", "workout_id": 3, "target_id": 3},
    {"username": "john_doe", "date": "2024-08-09", "workout_id": 3, "target_id": 4},
    {"username": "robert_brown", "date": "2024-08-09", "workout_id": 2, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-09", "workout_id": 1, "target_id": 3},
    {"username": "emily_jones", "date": "2024-08-09", "workout_id": 3, "target_id": 1},
    {"username": "emily_jones", "date": "2024-08-09", "workout_id": 4, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-09", "workout_id": 2, "target_id": 4},
    {"username": "michael_taylor", "date": "2024-08-09", "workout_id": 6, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-09", "workout_id": 1, "target_id": 4},
    {"username": "john_doe", "date": "2024-08-10", "workout_id": 5, "target_id": 2},
    {"username": "jane_smith", "date": "2024-08-10", "workout_id": 6, "target_id": 2},
    {"username": "jane_smith", "date": "2024-08-10", "workout_id": 2, "target_id": 3},
    {"username": "robert_brown", "date": "2024-08-10", "workout_id": 3, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-10", "workout_id": 4, "target_id": 2},
    {"username": "robert_brown", "date": "2024-08-10", "workout_id": 2, "target_id": 3},
    {"username": "emily_jones", "date": "2024-08-10", "workout_id": 1, "target_id": 1},
    {"username": "emily_jones", "date": "2024-08-10", "workout_id": 1, "target_id": 3},
    {"username": "emily_jones", "date": "2024-08-10", "workout_id": 3, "target_id": 4},
    {"username": "michael_taylor", "date": "2024-08-10", "workout_id": 2, "target_id": 1},
    {"username": "michael_taylor", "date": "2024-08-10", "workout_id": 2, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-10", "workout_id": 3, "target_id": 4},
    {"username": "john_doe", "date": "2024-08-11", "workout_id": 1, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-11", "workout_id": 6, "target_id": 2},
    {"username": "john_doe", "date": "2024-08-11", "workout_id": 1, "target_id": 3},
    {"username": "john_doe", "date": "2024-08-11", "workout_id": 2, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-11", "workout_id": 1, "target_id": 1},
    {"username": "jane_smith", "date": "2024-08-11", "workout_id": 3, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-11", "workout_id": 2, "target_id": 3},
    {"username": "robert_brown", "date": "2024-08-11", "workout_id": 5, "target_id": 2},
    {"username": "robert_brown", "date": "2024-08-11", "workout_id": 4, "target_id": 2},
    {"username": "robert_brown", "date": "2024-08-11", "workout_id": 6, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-11", "workout_id": 5, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-11", "workout_id": 1, "target_id": 1},
    {"username": "michael_taylor", "date": "2024-08-11", "workout_id": 2, "target_id": 4},
    {"username": "michael_taylor", "date": "2024-08-11", "workout_id": 4, "target_id": 2},
    {"username": "john_doe", "date": "2024-08-12", "workout_id": 3, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-12", "workout_id": 5, "target_id": 2},
    {"username": "john_doe", "date": "2024-08-12", "workout_id": 1, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-12", "workout_id": 2, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-12", "workout_id": 3, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-12", "workout_id": 4, "target_id": 2},
    {"username": "robert_brown", "date": "2024-08-12", "workout_id": 1, "target_id": 4},
    {"username": "emily_jones", "date": "2024-08-12", "workout_id": 2, "target_id": 1},
    {"username": "emily_jones", "date": "2024-08-12", "workout_id": 4, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-12", "workout_id": 6, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-12", "workout_id": 1, "target_id": 3},
    {"username": "john_doe", "date": "2024-08-13", "workout_id": 2, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-13", "workout_id": 3, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-13", "workout_id": 5, "target_id": 2},
    {"username": "robert_brown", "date": "2024-08-13", "workout_id": 1, "target_id": 3},
    {"username": "emily_jones", "date": "2024-08-13", "workout_id": 2, "target_id": 4},
    {"username": "michael_taylor", "date": "2024-08-13", "workout_id": 3, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-13", "workout_id": 4, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-14", "workout_id": 5, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-14", "workout_id": 2, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-14", "workout_id": 3, "target_id": 4},
    {"username": "emily_jones", "date": "2024-08-14", "workout_id": 1, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-14", "workout_id": 1, "target_id": 4},
    {"username": "john_doe", "date": "2024-08-15", "workout_id": 2, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-15", "workout_id": 4, "target_id": 2},
    {"username": "robert_brown", "date": "2024-08-15", "workout_id": 6, "target_id": 1},
    {"username": "emily_jones", "date": "2024-08-15", "workout_id": 1, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-15", "workout_id": 2, "target_id": 1},
    {"username": "michael_taylor", "date": "2024-08-15", "workout_id": 3, "target_id": 4},
    {"username": "john_doe", "date": "2024-08-16", "workout_id": 1, "target_id": 2},
    {"username": "jane_smith", "date": "2024-08-16", "workout_id": 4, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-16", "workout_id": 3, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-16", "workout_id": 2, "target_id": 4},
    {"username": "michael_taylor", "date": "2024-08-16", "workout_id": 1, "target_id": 3},
    {"username": "john_doe", "date": "2024-08-17", "workout_id": 5, "target_id": 1},
    {"username": "jane_smith", "date": "2024-08-17", "workout_id": 2, "target_id": 3},
    {"username": "robert_brown", "date": "2024-08-17", "workout_id": 1, "target_id": 4},
    {"username": "emily_jones", "date": "2024-08-17", "workout_id": 4, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-17", "workout_id": 1, "target_id": 3},
    {"username": "john_doe", "date": "2024-08-18", "workout_id": 2, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-18", "workout_id": 3, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-18", "workout_id": 4, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-18", "workout_id": 1, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-18", "workout_id": 5, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-19", "workout_id": 2, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-19", "workout_id": 4, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-19", "workout_id": 1, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-19", "workout_id": 3, "target_id": 4},
    {"username": "michael_taylor", "date": "2024-08-19", "workout_id": 6, "target_id": 2},
    {"username": "john_doe", "date": "2024-08-20", "workout_id": 1, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-20", "workout_id": 2, "target_id": 4},
    {"username": "robert_brown", "date": "2024-08-20", "workout_id": 3, "target_id": 1},
    {"username": "emily_jones", "date": "2024-08-20", "workout_id": 4, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-20", "workout_id": 5, "target_id": 3},
    {"username": "john_doe", "date": "2024-08-21", "workout_id": 1, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-21", "workout_id": 2, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-21", "workout_id": 3, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-21", "workout_id": 4, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-21", "workout_id": 5, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-22", "workout_id": 2, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-22", "workout_id": 3, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-22", "workout_id": 4, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-22", "workout_id": 1, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-22", "workout_id": 5, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-23", "workout_id": 2, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-23", "workout_id": 4, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-23", "workout_id": 1, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-23", "workout_id": 3, "target_id": 4},
    {"username": "michael_taylor", "date": "2024-08-23", "workout_id": 6, "target_id": 2},
    {"username": "john_doe", "date": "2024-08-24", "workout_id": 1, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-24", "workout_id": 2, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-24", "workout_id": 3, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-24", "workout_id": 4, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-24", "workout_id": 5, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-25", "workout_id": 2, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-25", "workout_id": 3, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-25", "workout_id": 4, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-25", "workout_id": 1, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-25", "workout_id": 6, "target_id": 2},
    {"username": "john_doe", "date": "2024-08-26", "workout_id": 1, "target_id": 3},
    {"username": "jane_smith", "date": "2024-08-26", "workout_id": 2, "target_id": 4},
    {"username": "robert_brown", "date": "2024-08-26", "workout_id": 3, "target_id": 1},
    {"username": "emily_jones", "date": "2024-08-26", "workout_id": 4, "target_id": 2},
    {"username": "michael_taylor", "date": "2024-08-26", "workout_id": 5, "target_id": 3},
    {"username": "john_doe", "date": "2024-08-27", "workout_id": 2, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-27", "workout_id": 3, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-27", "workout_id": 4, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-27", "workout_id": 1, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-27", "workout_id": 6, "target_id": 2},
    {"username": "john_doe", "date": "2024-08-28", "workout_id": 1, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-28", "workout_id": 2, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-28", "workout_id": 3, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-28", "workout_id": 4, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-28", "workout_id": 5, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-29", "workout_id": 2, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-29", "workout_id": 3, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-29", "workout_id": 4, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-29", "workout_id": 1, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-29", "workout_id": 6, "target_id": 2},
    {"username": "john_doe", "date": "2024-08-30", "workout_id": 1, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-30", "workout_id": 2, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-30", "workout_id": 3, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-30", "workout_id": 4, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-30", "workout_id": 5, "target_id": 1},
    {"username": "john_doe", "date": "2024-08-31", "workout_id": 2, "target_id": 4},
    {"username": "jane_smith", "date": "2024-08-31", "workout_id": 3, "target_id": 1},
    {"username": "robert_brown", "date": "2024-08-31", "workout_id": 4, "target_id": 2},
    {"username": "emily_jones", "date": "2024-08-31", "workout_id": 1, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-08-31", "workout_id": 6, "target_id": 2},
    {"username": "john_doe", "date": "2024-09-01", "workout_id": 1, "target_id": 4},
    {"username": "jane_smith", "date": "2024-09-01", "workout_id": 2, "target_id": 1},
    {"username": "robert_brown", "date": "2024-09-01", "workout_id": 3, "target_id": 2},
    {"username": "emily_jones", "date": "2024-09-01", "workout_id": 4, "target_id": 3},
    {"username": "michael_taylor", "date": "2024-09-01", "workout_id": 5, "target_id": 1},
]

for user in users:
    create_user(user["username"], user["email"])

for target in targets:
    create_targets(target["username"], target["month"], target["back_and_shoulder_target"], target["arms_target"], target["core_target"], target["legs_target"], target["back_and_shoulder_progress"], target["arms_progress"], target["core_progress"], target["legs_progress"])

for muscle in muscles:
    create_muscle(muscle["muscle_name"], muscle["explanation"], muscle["body_section_id"])

for exercise in exercises:
    create_exercise(exercise["exercise_name"], exercise["reps"], exercise["sets"], exercise["muscle_id"], exercise["intensity_id"])

for body_section in body_sections:
    create_body_section(body_section["body_section_name"])

for session in sessions:
    create_session(session["username"], session["date"], session["workout_id"], session["target_id"])

for workout in workouts:
    create_workout(workout["workout_name"], workout["intensity"], workout["body_section_id"])